- defaults:
    shell:
      quiet: false
      stdin: true
      stdout: true
      stderr: true

- shell:
  - 'docker-compose -f docker/homeassistant/docker-compose.yml up -d'
  - 'docker exec pihole pihole -w t.co analytics.twitter.com'
  - 'docker exec pihole pihole -w graph.instagram.com'
  - 'docker exec pihole pihole -w www.googleadservices.com analytics.google.com'
  - 'docker exec pihole pihole -l off'
