#!/usr/bin/env bash

set -e

bold=$(tput bold)
normal=$(tput sgr0)

BASE_CONFIGS="base"
EXECUTE_PULL=true
SAVE_CONFIG=false
PROFILES_TO_INSTALL=()
# Loop through arguments and process them
for arg in "$@"
do
  case $arg in
    --pull)
      EXECUTE_PULL=true
      shift 
      ;;
    --no-pull)
      EXECUTE_PULL=no
      shift 
      ;;
    --save-config)
      SAVE_CONFIG=true
      shift
      ;;
    --base-configs=*)
      BASE_CONFIGS="${arg#*=}"
      shift
      ;;
    *)
      PROFILES_TO_INSTALL+=("$1")
      shift 
      ;;
  esac
done

CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIGS_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if $SAVE_CONFIG; then
  echo "#!/usr/bin/env bash" > refresh-dotfiles
  echo "cd $BASE_DIR" >> refresh-dotfiles
  if $EXECUTE_PULL; then pull_string="--pull"; else pull_string="--no-pull"; fi
  profile_list=$( IFS=$' '; echo "${PROFILES_TO_INSTALL[*]}" )
  echo "$BASE_DIR/install-profile $pull_string --base-configs=$BASE_CONFIGS $profile_list" >> refresh-dotfiles
fi

CONFIG_FILES=()
IFS=',' read -ra BASE_CONFIGS_ARRAY <<< "$BASE_CONFIGS"
echo "${bold}Base configs: ${BASE_CONFIGS_ARRAY[*]}"
for config in ${BASE_CONFIGS_ARRAY[@]}
do
  CONFIG_FILES+=("${BASE_DIR}/${META_DIR}/${config}${CONFIG_SUFFIX}")
done

echo "${bold}Profiles: ${PROFILES_TO_INSTALL[*]}"

for profile in ${PROFILES_TO_INSTALL[@]}
do
  while IFS= read -r config
  do
    CONFIG_FILES+=("${BASE_DIR}/${META_DIR}/${CONFIGS_DIR}/${config}${CONFIG_SUFFIX}"); 
  done < "${BASE_DIR}/${META_DIR}/${PROFILES_DIR}/${profile}"      
done

for file in ${CONFIG_FILES[@]}
do
  echo "${bold}Processing file $file"
  "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "$file"
done
