#!/bin/zsh
# Wrapper script around git binary.
# Note: relatively fragile. if `whereis git` returns a different
# ordering, this may break.
if [[ $PWD =~ '^/google/src/' ]];then
    # return 1 so that git_prompt_info returns 0
    exit 1
else
    # get list of candidates, split into array
    local gits=("${(@s: :)$(whereis -b git)}")
    # call the first one in the list
    exec $gits[2] "$@"
fi
