set nocompatible
set mouse=a

filetype off

" set the runtime path to include Vundle and initialize
set runtimepath^=~/.vim/bundle/bbye
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
  " let Vundle manage Vundle, required
  Plugin 'VundleVim/Vundle.vim'

  Plugin 'benmills/vimux'
  Plugin 'christoomey/vim-tmux-navigator'
  Plugin 'google/vim-codefmt'
  Plugin 'google/vim-glaive'
  Plugin 'google/vim-maktaba'
  Plugin 'scrooloose/nerdcommenter'
  Plugin 'tpope/vim-sensible'
  "Not working on Raspberry pi
  "Plugin 'Valloric/MatchTagAlways'
  " Not working in my installs other than glinux
  "Plugin 'SirVer/ultisnips'

  " Snippets for ultisnips are separated from the engine. keep as last.
  "Plugin 'honza/vim-snippets'
" All of your Plugins must be added before the following line
call vundle#end()            " required
call glaive#Install()

" Optional: Enable codefmt's default mappings on the <Leader>= prefix.
Glaive codefmt plugin[mappings]

filetype plugin indent on
" syntax highlighting
syntax on
" use » to mark Tabs and ° to mark trailing whitespace. This is a
" non-obtrusive way to mark these special characters.
set list listchars=tab:»\ ,trail:°

" Highlight the search term when you search for it.
set hlsearch

" By default, it looks up man pages for the word under the cursor, which isn't
" very useful, so we map it to something else.
nnoremap <s-k> <CR>

set expandtab
set tabstop=2
set shiftwidth=2
set textwidth=80

" set UTF-8 encoding
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

" use indentation of previous line
set autoindent

" use intelligent indentation for C
set smartindent

" turn syntax highlighting on
set t_Co=256

" turn line numbers on
set number

" highlight matching braces
set showmatch

" intelligent comments
set comments=sl:/*,mb:\ *,elx:\ */
augroup autoformat_settings
  autocmd FileType bzl AutoFormatBuffer buildifier
  autocmd FileType c,cpp,proto,javascript,arduino AutoFormatBuffer clang-format
  autocmd FileType dart AutoFormatBuffer dartfmt
  autocmd FileType go AutoFormatBuffer gofmt
  autocmd FileType gn AutoFormatBuffer gn
  autocmd FileType html,css,sass,scss,less,json AutoFormatBuffer js-beautify
  autocmd FileType java AutoFormatBuffer google-java-format
  autocmd FileType python AutoFormatBuffer yapf
  " Alternative: autocmd FileType python AutoFormatBuffer autopep8
  autocmd FileType rust AutoFormatBuffer rustfmt
  autocmd FileType vue AutoFormatBuffer prettier
augroup END

" \v to generate new vertical split
nnoremap <leader>v :vsplit<CR>
" \s to generate new vertical split
nnoremap <leader>s :split<CR>
" \e to explore
nnoremap <leader>e :Explore<CR>

" \q to close buffer
nnoremap <Leader>q :Bdelete<CR>

" Prompt for a command to run
map <Leader>vp :VimuxPromptCommand<CR>
" Run last command executed by VimuxRunCommand
map <Leader>vl :VimuxRunLastCommand<CR>
" Zoom the tmux runner pane
map <Leader>vz :VimuxZoomRunner<CR>

