version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8000:80/tcp"
      - "4443:443/tcp"
    environment:
      TZ: 'America/New_York'
    volumes:
      - '~/docker/pihole-data/etc/pihole/:/etc/pihole/'
      - '~/docker/pihole-data/etc/dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
