# Brewfile
# Install `mas' before going forward
brew "mas"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
cask_args appdir: '/Applications'

brew "gh"

# Youtube-dl stuff
brew "youtube-dl"
brew "ffmpeg"
brew "aria2"

brew "adobe-creative-cloud"

# Streaming & Screen recording
cask "obs"
cask "blackhole-2ch"
cask "blackhole-16ch"
