# Brewfile
# Install `mas' before going forward
brew "mas"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
cask_args appdir: '/Applications'

brew "github/gh/gh"

cask "obs"

mas "Excel", id:462058435
mas "OneDrive", id:823766827
mas "Outlook", id:985367838
mas "PowerPoint", id:462062816
mas "Word", id:462054704
