# Brewfile
# Install `mas' before going forward
brew "mas"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
cask_args appdir: '/Applications'

brew "gh"

# Youtubedl stuff
brew "youtube-dl"
brew "ffmpeg"
brew "aria2"


cask "obs"
cask "blackhole-2ch"
cask "blackhole-16ch"

mas "Excel", id:462058435
mas "PowerPoint", id:462062816
mas "Word", id:462054704
