# Brewfile
brew "cask"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
cask_args appdir: '/Applications'

# Moved to Brewfile_mas since it doesn't work on gh actions
# brew "go"
brew "graphviz"
brew "pre-commit"
brew "python"
brew "python3"
brew "rust"
brew "sbt"
brew "scala"
brew "vim"

cask "basictex"
cask "discord"
cask "github"
cask "netnewswire"
cask "signal"
cask "steam"
cask "visual-studio-code"
cask "vlc"
