version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=America/New_York
    mac_address: 28:F6:88:88:88:88
    networks:
      br6:
        ipv4_address: 192.168.6.11
    devices:
      - '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_31600458-if00-port0:/dev/zwave'
    volumes:
      - ~/docker/zwavejs2mqtt:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ~/docker/mosquitto:/mosquitto/:rw
    mac_address: 28:F6:77:77:77:77
    networks:
      br6:
        ipv4_address: 192.168.6.12
    ports:
      - 1883:1883
      - 9001:9001

  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    mac_address: 28:F6:55:6E:3F:04
    networks:
      br6:
        ipv4_address: 192.168.6.2
    environment:
      - TZ=America/New_York
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=80
    volumes:
      - ~/docker/homebridge:/homebridge
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: always
    mac_address: 28:F6:55:6E:3F:15
    networks:
      br6:
        ipv4_address: 192.168.6.10
    devices:
      - '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_31600458-if01-port0:/dev/zigbee'
    environment:
      - TZ=America/New_York
    volumes:
      - ~/docker/homeassistant:/config

networks:
  br6:
    driver: macvlan
    driver_opts:
      parent: enxb827eb3ab21e
    ipam:
      driver: default
      config:
        - subnet: 192.168.6.0/24
