version: '3.7'
services:
  zwave-js-ui:
    container_name: zwave-js-ui #image: zwavejs/zwave-js-ui:latest
    image: sha256:c4cc7f09ad90c27072bf13279690413815298cb6cdabc5e8335d458eb5a5ee8a
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=America/New_York
    mac_address: 28:F6:88:88:88:88
    networks:
      vlan:
        ipv4_address: 192.168.6.11
    devices:
      - '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_31600458-if00-port0:/dev/zwave'
    volumes:
      - ~/docker/zwavejs2mqtt:/usr/src/app/store #- ~/docker/zwavejsui:/usr/src/app/store
    # ports:
    #   - '8091:8091' # port for web interface
    #   - '3000:3000' # port for Z-Wave JS websocket server

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ~/docker/mosquitto:/mosquitto/:rw
    mac_address: 28:F6:77:77:77:77
    networks:
      vlan:
        ipv4_address: 192.168.6.12

  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    mac_address: 28:F6:55:6E:3F:04
    networks:
      vlan:
        ipv4_address: 192.168.6.2
    environment:
      - TZ=America/New_York
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=80
    volumes:
      - ~/docker/homebridge:/homebridge
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: always
    mac_address: 28:F6:55:6E:3F:15
    networks:
      vlan:
        ipv4_address: 192.168.6.10
    devices:
      - '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_31600458-if01-port0:/dev/zigbee'
    environment:
      - TZ=America/New_York
    volumes:
      - ~/docker/homeassistant:/config

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    mac_address: 28:F6:55:56:78:9A
    environment:
      - PORT=80
    networks:
      vlan:
        ipv4_address: 192.168.6.5
    volumes:
      - ~/docker/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    mac_address: 28:F6:55:56:00:00
    networks:
      vlan:
        ipv4_address: 192.168.6.4
    environment:
      TZ: 'America/New_York'
    volumes:
      - '~/docker/pihole-data/etc/pihole/:/etc/pihole/'
      - '~/docker/pihole-data/etc/dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always

networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: enxb827eb3ab21e
    ipam:
      driver: default
      config:
        - subnet: 192.168.6.0/24
